### PR TITLE
Feature/alarm boardcase manager

### PR DESCRIPTION
**Pull request by GWJian**
alarm boardcase manager

### CODE REVIEW

**Review by JonesLim — APPROVED** [review]
Good job!

**Review by JonesLim — CHANGES_REQUESTED** [review]
Remove the comments

**Review by JonesLim — CHANGES_REQUESTED** [review]
Remove unnecessary codes

**Review by CmdreSnackers — APPROVED** [review]
function to turn on and off specific notifications working,

**Comment by GWJian** [comment]
> Remove unnecessary codes

i need them fornow,will remove nxt time

**Review by JonesLim — APPROVED** [review]

**Pull request merged**
